### ISSUE TITLE
Please add these websites to the whitelist

### ISSUE THREAD

**Issue by Marek33** [AdroitAdorKhan/EnergizedProtection#52]
After the latest Energized Unified Protection update (uBlock Origin version), the YouTube is almost completely broken, unless I whitelisted it. I can't see the comments, watch videos and see thumbnails, but when I whitelist YouTube in the Ublock Origin, it shows the adds so the whole point of having your filter is lost for me.

However, more important is that there are certain websites, which are blocked, and they are not usable without whitelisting. I have been using them for years, and never noticed any virus or malware on those sites. Here is the list: _Crymods.net, NexusMods.com, Moddb.com, Mozilla.net, Google Translate, Pcgamingwiki.com, Languagetool.org,_ and even the _Github_.

I tried this on multiple browsers and its broken for both, Chromium and Firefox forks.

EDIT: These websites seem to be affected as well: _hdproject.altervista.org, Gamefront.com, drive.google.com, duckduckgo.com, and forum.worldofplayers.de_. I'm not completely sure how virus free are these four websites, but they shouldn't have its content, completely blocked they have it now: www.gamepressure.com, game-mafia2.Ru, mafiamods.com and uloz.to.

There is also one site, which definitely has some shady stuff going on, but the normal filters should cover that: **https://gamemodding.com/en/** Not only that it has excellent modifications like the _Trees Project 3.0_ for the Mafia 1 there are other nice Mods.

**Comment by AdroitAdorKhan** [comment]
Kindly check uBlock again and make sure you are using Energized Protection Unified only. Because without `moddb.com`, everything else is whitelisted and won't get blocked ever. I think, there's something wrong from your side. Check again and let me know.

**Comment by Marek33** [comment]
I checked it again, and I had the same issues again. I had all the filters from the Ublock Origin and I disabled them all + language filters. Unfortunately, I still had that issue with all sites. Plus, I disabled every other extension, as well, as the Firefox/Brave Shields so, there wouldn't be any other elements blocking the site.

The _pcgamingwiki.com_ is mostly fine, except the community tab, which has a white background with a lot of text. That is, for most of the other websites, which I mentioned before, except the few which had other issues. For _DuckDuckGo_, its only the search results, for _Google Drive_ its the files, for _mafiamods.com_ is the pictures of Mods, the _gamemodding.com/en/_ has a few elements blocked on the main page, but a way more on the other pages. The _forum.worldofplayers.de_ has the Gothic games at the top of the thread missing like here: _https://forum.worldofplayers.de/forum/threads/1340357-Release-Gothic-%C2%BD-%C2%97-SystemPack-%28ENG-DEU%29_ Only the _mozzila.net_ is not broken for the **Firefox**, where I'm checking for extensions, but it is broken for **Chromium**. Some websites like the **windy.com** has almost completely blank page. Some are only a bit broken, and simply allow element, like the **lightningmaps.org** makes the site function correctly again. Rest of the sites, are like they were before.

However, it's not that the websites would be blocked, but it hides a lot of stuff, which it should be shown like logos, images and so on. I hope that you didn't mean, that the sites are completely blocked since they aren't, but unless I tick the **I am an advanced user** in the Ublock Origin, I can't whitelist those elements, and I don't think that most people understand that.

BTW: Thanks for a very soon response!

**Comment by badmojr** [comment]
Hey, @Marek33.
Whick pack do you have enabled? ( a URL would be helpful).

**Comment by Marek33** [comment]
What do you mean by the Pack? There are multiple versions on the FilterList website, and the one which has most filters is the **Unified Protection** version and that's my version like I said before.

**Comment by badmojr** [comment]
Great! How about some screenshots of everything that's broken?
Make make a different comment for each issue.

In the case above, too much information is crammed in a single post.
Personally, I tend to look for the main idea(s) & not read the whole post.
That's how I missed which Energized pack you've got enabled.

**Comment by Marek33** [comment]
I see, and here are the screenshots: 

Only the **NexusMods** (which were more broken yesterday) and the **Mafia Mods,** are a bit broken, all the other websites are completely broken unless I use the whitelist function.

Once again, I disabled all other filters, expect language ones, and the other ones, in the **Ublock Origin.** Brave Adblock was disabled, but I forgot to disable the conversion to the HTTPS on some sites. However, it doesn't make a single difference after I disabled it, and use a new link to open the site. As for Firefox, all web sites load the same, so I don't see a point of making screenshots for it, expect the extension store, which is completely fine on that platform.

Also, please in the future, properly read my previous posts, so you wouldn't be confused next time.

**Comment by badmojr** [comment]
You realize I'm just lending you a hand, ryt?
So, you can't just be demanding that I do this & that.. (I find it quite offensive).

I get it. You are upset.
But if we'd all get emotions get in the way, things could get really ugly real fast.

**Comment by Marek33** [comment]
I understand, but why are you offended? I send you the link with the images like you wanted, and I couldn't upload it here, since Github sucks. No offense, but Discord for example, is way better.

I know, but I would prefer, if the people would read, what is posted, so I wouldn't need to mention things, which I already wrote somewhere.

No, I'm not, I just don't know what exactly you want. And I don't understand why you gave me two confused emojis, when it was mostly properly written. I'm not upset, confused or angry, but I don't get, that a lot of websites have so many blocked elements. And especially, why is Moddb blocked, if it's a great virus free website.

**Comment by badmojr** [comment]
Basically, here's why it's blocked.
"[Energized Protection] consolidates several reputable filters, and merges them into couple of protection packs ..."

About the emojis! They gone. Happy?

**Comment by Marek33** [comment]
I see, but why aren't the websites either completely blocked, or only the dangerous things are blocked? Why make so many websites not being able to function, with a simple whitelisting? There are even some news sites, from my country, which have blocked the Google Fonts, which I think are trustworthy.

Thanks, and no problem!

**Comment by badmojr** [comment]
Really? You are asking why some sites are broken?
well.. 'coz of crowdsourcing.

**Comment by Marek33** [comment]
Yes, I do. And there is no need for that, since most of those websites are virus free. It just doesn't make sense to block certain functioning elements, instead of blocking an entire website, like with the Moddb.

**Comment by Marek33** [comment]
@AdroitAdorKhan 

Thank you very much! After the Friday update, all the issues, which I listed, and much more are now fixed! And thanks for Whitelisting Moddb!

Once again thank you for fixing those issues and also for making this excellent protection pack!
