### ISSUE TITLE
Videoder app API domains api.videoder.net and static.videoder.net being blocked 

### ISSUE THREAD

**Issue by surahul** [AdroitAdorKhan/EnergizedProtection#56]
Videoder - https://www.videoder.com app's API is being blocked and thus making the app unstable to use. 

![image](https://user-images.githubusercontent.com/4014692/65657130-cab60a00-e03f-11e9-9fd7-07052d50ca6d.png)

**Comment by AdroitAdorKhan** [comment]
It will be fixed on next update.
