### ISSUE TITLE
Chromium - All websites with the letter H are blocked

### ISSUE THREAD

**Issue by Marek33** [AdroitAdorKhan/EnergizedProtection#63]
I have no idea, what has happened, but after the latest update all the websites, with the letter H are blocked. No matter if they are in English, Slovak, Czech or in other languages they are on a blacklist. Yes, even the Github is blocked. It seems that this only happens to the Chromium Browsers, and not for the Firefox or Waterfox.

I'm using the Energized Ultimate Protection.

**Comment by Marek33** [comment]
@AdroitAdorKhan Now, this is a very interesting thing. It seems, that this bug, is only at the Ungoogled and Iridium. Brave and Chrome (thought, only tested on Canary), doesn't have this issue, but the first two have. Can you fix it somehow?

**Comment by kataki** [comment]
there’s a wrong line in the core list that is causing this issue 
0.0.0.0 h

**Comment by Marek33** [comment]
@kataki Thanks for info! Hopefully it will be fixed soon.

**Comment by Marek33** [comment]
It seems that this issue has been fixed, but there are still a lot of broken websites.
