### ISSUE TITLE
wget Server error HTTPS://1.1 404 not found

### ISSUE THREAD

**Issue by ExoSH** [AdroitAdorKhan/EnergizedProtection#73]
There is this issue that appears after Installing the Module again.

I updated:

`> wget / openssl / ca-certificates`

but I could not fix the Issue. May anyone help me further here? how do I fix this?

thanks for commenting.

**Comment by AdroitAdorKhan** [comment]
Can you check new beta builds [here](https://github.com/EnergizedProtection/magisk/releases).

**Comment by ExoSH** [comment]
> Can you check new beta builds [here](https://github.com/EnergizedProtection/magisk/releases).

Do I need to extract them in EnergizedProtection Folder?

**Comment by AdroitAdorKhan** [comment]
Check there. Download the beta zip and flash via Magisk Manager.

**Comment by ExoSH** [comment]
thank you, worked on my Device! I'll close this Issue.
